s/OPENSHIFT_TOMCAT/OPENSHIFT_TOMEE/g

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -5,32 +5,32 @@ case "$1" in
     version="$2"
 esac
 
-SYSTEM_TOMCAT_DIR="/opt/apache-tomee-${version}"
+SYSTEM_TOMEE_DIR="/opt/apache-tomee-${version}"
 
-if [ ! -d ${SYSTEM_TOMCAT_DIR} ]; then
-  echo "Couldn't find system tomcat dir at ${SYSTEM_TOMCAT_DIR}" 1>&2
+if [ ! -d ${SYSTEM_TOMEE_DIR} ]; then
+  echo "Couldn't find system tomcat dir at ${SYSTEM_TOMEE_DIR}" 1>&2
   exit 127
 fi
 
-mkdir -p ${OPENSHIFT_TOMCAT_DIR}/{run,tmp,conf,logs}
+mkdir -p ${OPENSHIFT_TOMEE_DIR}/{run,tmp,conf,logs}
 mkdir -p ${OPENSHIFT_HOMEDIR}/.m2
 
 # Set up the config directory in the user repository template
-cp ${OPENSHIFT_TOMCAT_DIR}/versions/{shared,${version}}/configuration/* ${OPENSHIFT_TOMCAT_DIR}/template/.openshift/config
+cp ${OPENSHIFT_TOMEE_DIR}/versions/{shared,${version}}/configuration/* ${OPENSHIFT_TOMEE_DIR}/template/.openshift/config
 
 # Link the system Tomcat binaries to the cart Tomcat instance directory
-ln -sf ${SYSTEM_TOMCAT_DIR}/bin/bootstrap.jar ${OPENSHIFT_TOMCAT_DIR}/bin/bootstrap.jar
-ln -sf ${SYSTEM_TOMCAT_DIR}/bin/commons-daemon.jar ${OPENSHIFT_TOMCAT_DIR}/bin/commons-daemon.jar
-ln -sf ${SYSTEM_TOMCAT_DIR}/bin/tomcat-juli.jar ${OPENSHIFT_TOMCAT_DIR}/bin/tomcat-juli.jar
+ln -sf ${SYSTEM_TOMEE_DIR}/bin/bootstrap.jar ${OPENSHIFT_TOMEE_DIR}/bin/bootstrap.jar
+ln -sf ${SYSTEM_TOMEE_DIR}/bin/commons-daemon.jar ${OPENSHIFT_TOMEE_DIR}/bin/commons-daemon.jar
+ln -sf ${SYSTEM_TOMEE_DIR}/bin/tomcat-juli.jar ${OPENSHIFT_TOMEE_DIR}/bin/tomcat-juli.jar
 
 # Need to remove link -f gets confused as this is a link to a link
-[ -e ${OPENSHIFT_TOMCAT_DIR}/lib ] && rm ${OPENSHIFT_TOMCAT_DIR}/lib
-ln -sf ${SYSTEM_TOMCAT_DIR}/lib ${OPENSHIFT_TOMCAT_DIR}/lib
+[ -e ${OPENSHIFT_TOMEE_DIR}/lib ] && rm ${OPENSHIFT_TOMEE_DIR}/lib
+ln -sf ${SYSTEM_TOMEE_DIR}/lib ${OPENSHIFT_TOMEE_DIR}/lib
 
 # Link the user-controlled configurations to the Tomcat conf directory
-ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/web.xml ${OPENSHIFT_TOMCAT_DIR}/conf
-ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/tomcat-users.xml ${OPENSHIFT_TOMCAT_DIR}/conf
-ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/postgresql_module.xml ${OPENSHIFT_TOMCAT_DIR}/conf
-ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/catalina.properties ${OPENSHIFT_TOMCAT_DIR}/conf
-ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/catalina.policy ${OPENSHIFT_TOMCAT_DIR}/conf
-ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/logging.properties ${OPENSHIFT_TOMCAT_DIR}/conf
+ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/web.xml ${OPENSHIFT_TOMEE_DIR}/conf
+ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/tomcat-users.xml ${OPENSHIFT_TOMEE_DIR}/conf
+ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/postgresql_module.xml ${OPENSHIFT_TOMEE_DIR}/conf
+ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/catalina.properties ${OPENSHIFT_TOMEE_DIR}/conf
+ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/catalina.policy ${OPENSHIFT_TOMEE_DIR}/conf
+ln -sf ${OPENSHIFT_REPO_DIR}/.openshift/config/logging.properties ${OPENSHIFT_TOMEE_DIR}/conf
